name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged
        ports:
          - 5000:5000

    steps:
    # 1. Проверяем код из репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Настройка Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Установка зависимостей Python
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Запуск Python тестов
    - name: Run Python tests
      run: |
        pytest tests/ --maxfail=1 --disable-warnings -q

    # 5. Сборка Docker-образа
    - name: Build Docker image
      run: |
        docker build -t inventory-app .

    # 6. Настройка Java (для Maven)
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '25'

    # 7. Сборка Java-проекта через Maven
    - name: Build Java project
      run: |
        cd Java-demo
        mvn clean install

    # 8. (Опционально) Запуск Docker-контейнера
    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 inventory-app
